package com.entrofine.ifactor.app.entity;

public enum AppRole {
	ADMIN, SELLER, BUYER, VPBANK, PRE_SELLER, PRE_BUYER, PRE_SELLER_VIEW, PRE_SELLER_UPDATEAPP, PRE_SELLER_UPDATE, PRE_BUYER_VIEW, PRE_BUYER_UPDATEAPP, PRE_BUYER_UPDATE
}
